# app/config/security.yml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    encoders:
        "FOS\UserBundle\Model\UserInterface": sha512
    acl:
        connection: default

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                default_target_path: /refs
            logout:
                path: /logout
                target: /refs
            anonymous:    true

    access_control:
#        - { path: ^/author, role: ROLE_USER }
        - { path: ^/author/new, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/upload, role: ROLE_USER }
        - { path: ^/article/new, role: ROLE_USER }
        - { path: ^/unpublished/new, role: ROLE_USER }
        - { path: ^/inproceedings/new, role: ROLE_USER }
        - { path: ^/book/new, role: ROLE_USER }
        - { path: ^/editor/new, role: ROLE_USER }
        - { path: ^/edicion/new, role: ROLE_USER }
        - { path: ^/proceedings/new, role: ROLE_USER }
        - { path: ^/inbook/new, role: ROLE_USER }
        - { path: ^/arxiv, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
